"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class IMU(object):
    __slots__ = ["quaternion", "gyroscope", "accelerometer", "rpy", "temperature"]

    __typenames__ = ["float", "float", "float", "float", "int8_t"]

    __dimensions__ = [[4], [3], [3], [3], None]

    def __init__(self):
        self.quaternion = [ 0.0 for dim0 in range(4) ]
        self.gyroscope = [ 0.0 for dim0 in range(3) ]
        self.accelerometer = [ 0.0 for dim0 in range(3) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.temperature = 0

    def encode(self):
        buf = BytesIO()
        buf.write(IMU._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.quaternion[:4]))
        buf.write(struct.pack('>3f', *self.gyroscope[:3]))
        buf.write(struct.pack('>3f', *self.accelerometer[:3]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack(">b", self.temperature))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != IMU._get_packed_fingerprint():
            raise ValueError("Decode error")
        return IMU._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = IMU()
        self.quaternion = struct.unpack('>4f', buf.read(16))
        self.gyroscope = struct.unpack('>3f', buf.read(12))
        self.accelerometer = struct.unpack('>3f', buf.read(12))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.temperature = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if IMU in parents: return 0
        tmphash = (0x53a6be455f9e22fa) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if IMU._packed_fingerprint is None:
            IMU._packed_fingerprint = struct.pack(">Q", IMU._get_hash_recursive([]))
        return IMU._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

