"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class BmsCmd(object):
    __slots__ = ["off", "reserve"]

    def __init__(self):
        self.off = 0
        self.reserve = [ 0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(BmsCmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.off))
        buf.write(struct.pack('>3b', *self.reserve[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != BmsCmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return BmsCmd._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = BmsCmd()
        self.off = struct.unpack(">b", buf.read(1))[0]
        self.reserve = struct.unpack('>3b', buf.read(3))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if BmsCmd in parents: return 0
        tmphash = (0xeb007e7afc9b7913) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if BmsCmd._packed_fingerprint is None:
            BmsCmd._packed_fingerprint = struct.pack(">Q", BmsCmd._get_hash_recursive([]))
        return BmsCmd._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

